#!/usr/bin/env bash
# Generated by ChatGPT.
# Generate JPEG XL (.jxl) files under static/jxl mirroring content/ paths for Hugo builds.
# Minimal, fail-fast script: no dry-run, no extras.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONTENT="${ROOT}/content"
STATIC_JXL="${ROOT}/static/jxl"

# Require cjxl (libjxl tools)
command -v cjxl >/dev/null 2>&1 || {
  echo "Error: 'cjxl' (JPEG XL encoder) is not installed."
  echo "Install instructions:"
  echo "  - macOS (Homebrew): brew install jpeg-xl"
  echo "  - Ubuntu/Debian: sudo apt-get install libjxl-tools (or build from source)"
  echo "  - Fedora: sudo dnf install libjxl-tools"
  echo "Please install 'cjxl' and rerun the build."
  exit 1
}
# Ensure content directory exists
[[ -d "${CONTENT}" ]] || { echo "content dir not found: ${CONTENT}"; exit 1; }
# Ensure static/jxl root exists
mkdir -p "${STATIC_JXL}"

# Tunables via environment variables
QUALITY="${JXL_QUALITY:-90}"   # 0-100
EFFORT="${JXL_EFFORT:-7}"      # 1-9

export LC_ALL=C

# Find common image types and generate .jxl into static/jxl mirroring content/ structure
find "${CONTENT}" -type f \( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \) -print0 |
while IFS= read -r -d '' src; do
  # Compute path relative to content/
  rel="${src#${CONTENT}/}"
  rel_dir="$(dirname "${rel}")"
  base="${rel##*/}"
  stem="${base%.*}"

  # Destination under static/jxl mirrors content/ directory layout
  out_dir="${STATIC_JXL}/${rel_dir}"
  jxl="${out_dir}/${stem}.jxl"

  # Ensure destination directory exists
  mkdir -p "${out_dir}"

  # Skip if existing .jxl is newer than the source
  if [[ -f "${jxl}" && "${jxl}" -nt "${src}" ]]; then
    echo "Up-to-date: ${jxl}"
    continue
  fi

  echo "Encode -> ${jxl} (from ${src})"
  cjxl "${src}" "${jxl}" --quality="${QUALITY}" --effort="${EFFORT}" || {
    echo "Error encoding: ${src}" >&2
    exit 2
  }
done
